### ISSUE TITLE
HUT : Solrizer

### ISSUE THREAD

**Issue by scherztc** [uclibs/ucrate#1137]
### Descriptive summary

  526) hyrax/base/_attributes.html.erb has links to search for other objects with the same metadata
       Failure/Error: Solrizer.solr_name('has_model', :symbol) => ["GenericWork"],
       
       NameError:
         uninitialized constant Solrizer
       # ./spec/views/hyrax/base/_attributes.html.erb_spec.rb:14:in `block (2 levels) in <top (required)>'
       # ./spec/views/hyrax/base/_attributes.html.erb_spec.rb:11:in `block (2 levels) in <top (required)>'
       # ./spec/views/hyrax/base/_attributes.html.erb_spec.rb:24:in `block (2 levels) in <top (required)>'
       # ./spec/views/hyrax/base/_attributes.html.erb_spec.rb:29:in `block (2 levels) in <top (required)>'

### Steps to reproduce the behavior

1. Do this
1. Then do this...

### Related work

Link to related issues or prior related work here.

**Comment by scherztc** [comment]
Closed by JIRA : https://ucdts.atlassian.net/browse/LIBSCHOLAR-5?atlOrigin=eyJpIjoiN2I1N2I3OWRlNzY2NDM3NjhkOWVlMzQ1MzZkZGYwNWUiLCJwIjoiaiJ9
