### ISSUE TITLE
HUT : Collection Indexer Key Not Found

### ISSUE THREAD

**Issue by scherztc** [uclibs/ucrate#1141]
### Descriptive summary

638) Hyrax::CollectionIndexer#generate_solr_document removes leading articles
       Failure/Error: expect(subject.fetch('sort_title_ssi')).to eq("THE IS FIRST")
       
       KeyError:
         key not found: "sort_title_ssi"
       # ./spec/indexers/hyrax/collection_indexer_spec.rb:43:in `fetch'
       # ./spec/indexers/hyrax/collection_indexer_spec.rb:43:in `block (3 levels) in <top (required)>'

  639) Hyrax::CollectionIndexer#generate_solr_document has required fields
       Failure/Error: expect(subject.fetch('bytes_lts')).to eq(1000)
       
       KeyError:
         key not found: "bytes_lts"
       # ./spec/indexers/hyrax/collection_indexer_spec.rb:30:in `fetch'
       # ./spec/indexers/hyrax/collection_indexer_spec.rb:30:in `block (3 levels) in <top (required)>'

  640) Hyrax::CollectionIndexer#generate_solr_document removes leading spaces
       Failure/Error: expect(subject.fetch('sort_title_ssi')).to eq("I START WITH A SPACE")
       
       KeyError:
         key not found: "sort_title_ssi"
       # ./spec/indexers/hyrax/collection_indexer_spec.rb:38:in `fetch'
       # ./spec/indexers/hyrax/collection_indexer_spec.rb:38:in `block (3 levels) in <top (required)>'

  641) Hyrax::CollectionIndexer#generate_solr_document adds leading 0s as needed
       Failure/Error: expect(subject.fetch('sort_title_ssi')).to eq("00000000000000000001 IS THE FIRST TITLE")
       
       KeyError:
         key not found: "sort_title_ssi"
       # ./spec/indexers/hyrax/collection_indexer_spec.rb:63:in `fetch'
       # ./spec/indexers/hyrax/collection_indexer_spec.rb:63:in `block (3 levels) in <top (required)>'

  642) Hyrax::CollectionIndexer#generate_solr_document removes double spaces
       Failure/Error: expect(subject.fetch('sort_title_ssi')).to eq("THIS TITLE HAS EXTRA SPACES")
       
       KeyError:
         key not found: "sort_title_ssi"
       # ./spec/indexers/hyrax/collection_indexer_spec.rb:53:in `fetch'
       # ./spec/indexers/hyrax/collection_indexer_spec.rb:53:in `block (3 levels) in <top (required)>'

  643) Hyrax::CollectionIndexer#generate_solr_document upcases everything
       Failure/Error: expect(subject.fetch('sort_title_ssi')).to eq("I SHOULD BE UPPERCASE")
       
       KeyError:
         key not found: "sort_title_ssi"
       # ./spec/indexers/hyrax/collection_indexer_spec.rb:58:in `fetch'
       # ./spec/indexers/hyrax/collection_indexer_spec.rb:58:in `block (3 levels) in <top (required)>'

  644) Hyrax::CollectionIndexer#generate_solr_document removes non alphanumeric characters
       Failure/Error: expect(subject.fetch('sort_title_ssi')).to eq("TITLE 30 SURE HAS A LOT OF PUNCTUATION")
       
       KeyError:
         key not found: "sort_title_ssi"
       # ./spec/indexers/hyrax/collection_indexer_spec.rb:48:in `fetch'
       # ./spec/indexers/hyrax/collection_indexer_spec.rb:48:i

### Steps to reproduce the behavior

1. Do this
1. Then do this...

### Related work

Link to related issues or prior related work here.

**Comment by scherztc** [comment]
Closed by JIRA : https://ucdts.atlassian.net/browse/LIBSCHOLAR-5?atlOrigin=eyJpIjoiM2ZkNTEyNGQ1OTEzNGZiYzg4YTg1N2IwZjY1MzdkMDQiLCJwIjoiaiJ9
