### ISSUE TITLE
Deprecation Warning with IIIF Viewer

### ISSUE THREAD

**Issue by scherztc** [uclibs/ucrate#893]
### Descriptive summary

DEPRECATION WARNING: universal_viewer? is deprecated and will be removed from a future release (use iiif_viewer? instead). (called from _app_views_hyrax_base_show_html_erb__1369472397966666149_70156118571920 at /Users/scherztc/Workspace/ucrate/app/views/hyrax/base/show.html.erb:24) (2 times); e.g.: 
    /Users/scherztc/Workspace/ucrate/app/views/hyrax/base/show.html.erb:24:in `_app_views_hyrax_base_show_html_erb__1369472397966666149_70156118571920'
    /Users/scherztc/.rvm/gems/ruby-2.5.5@ucrate/gems/actionview-5.1.7/lib/action_view/template.rb:157:in `block in render'
    /Users/scherztc/.rvm/gems/ruby-2.5.5@ucrate/gems/activesupport-5.1.7/lib/active_support/notifications.rb:168:in `instrument'
    /Users/scherztc/.rvm/gems/ruby-2.5.5@ucrate/gems/actionview-5.1.7/lib/action_view/template.rb:352:in `instrument_render_template'
    /Users/scherztc/.rvm/gems/ruby-2.5.5@ucrate/gems/actionview-5.1.7/lib/action_view/template.rb:155:in `render'

      If you need more of the backtrace for any of these deprecations to identify
      where to make the necessary changes, you can configure 
      `Deprecation.default_deprecation_behavior = :raise`, and it will turn the deprecation
      warnings into errors, giving you the full backtrace.

### Expected behavior

use iiif_viewer? instead). (called from _app_views_hyrax_base_show_html_erb

### Actual behavior

Warning

### Steps to reproduce the behavior

1. Run test

**Comment by scherztc** [comment]
Closed by #1083
