### ISSUE TITLE
ClamAV error on Scholar QA

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#901]
### Descriptive summary

Scholar QA began having problem after recent RedHat updates.  The application would not start properly until the ClamAV gem was disabled.  Specific error listed below.

It's likely that ClamAV has been updated to a version that in incompatible with the clamav gem.  We may need to investigate a replacement like clamby.  It's likely that production Scholar will have this same problem when it gets its monthly updates in December.

```
rake aborted!
LoadError: libclamav.so.7: cannot open shared object file: No such file or directory - /srv/apps/scholar_capistrano/shared/vendor/bundle/ruby/2.5.0/gems/clamav-0.4.1/lib/clamav.so
/srv/apps/.gem/ruby/2.5.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:81:in `require'
/srv/apps/.gem/ruby/2.5.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
/srv/apps/.gem/ruby/2.5.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:76:in `each'
/srv/apps/.gem/ruby/2.5.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:76:in `block in require'
/srv/apps/.gem/ruby/2.5.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:65:in `each'
/srv/apps/.gem/ruby/2.5.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:65:in `require'
/srv/apps/.gem/ruby/2.5.0/gems/bundler-1.17.3/lib/bundler.rb:114:in `require'
/srv/apps/scholar_capistrano/releases/20200206201249/config/application.rb:9:in `<top (required)>'
/srv/apps/scholar_capistrano/releases/20200206201249/Rakefile:6:in `require_relative'
/srv/apps/scholar_capistrano/releases/20200206201249/Rakefile:6:in `<top (required)>'
```

**Comment by crowesn** [comment]
`clamscan -V` output
Prod: ClamAV 0.99.2/26096/Tue Mar  2 06:59:11 2021
QA: ClamAV 0.103.0/26097/Wed Mar  3 07:05:28 2021
